services:
  mongodb:
    image: mongo:latest
    container_name: integration-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
